[profile.default]
src = 'src'
out = 'out'
test = 'test'
libs = ['../../node_modules', "lib"]
fs_permissions = [{ access = "read-write", path = "./"}]
verbosity = 2
fuzz_runs = 256
fuzz_max_global_rejects = 100000000



remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  'openzeppelin-contracts/=node_modules/@openzeppelin/contracts/',
  'openzeppelin-contracts-upgradeable/=node_modules/openzeppelin-upgradeable/',
  'solmate/=lib/solmate/src/'
]


[rpc_endpoints]
FORKING_RPC_URL = "${FORKING_RPC_URL}"
ETH_RPC_URL = "${ETH_RPC_URL}"
POLYGON_RPC_URL = "${POLYGON_RPC_URL}"

[profile.ci]
src = 'src'
out = 'out'
test = 'test'
libs = ['../../node_modules', "lib"]

fs_permissions = [{ access = "read-write", path = "./"}]
verbosity = 2
fuzz_max_global_rejects = 100000000
fuzz_runs = 2500

remappings = [
  'ds-test/=lib/forge-std/lib/ds-test/src/',
  'forge-std/=lib/forge-std/src/',
  'openzeppelin-contracts/=node_modules/@openzeppelin/contracts/',
  'openzeppelin-contracts-upgradeable/=node_modules/openzeppelin-upgradeable/',
  'solmate/=lib/solmate/src/'
]

